server:
  port: 9081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5444/UserProfileDB
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update